repos:
-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/PyCQA/bandit
    rev: master
    hooks:
    - id: bandit

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v1.2.3
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      args: [--max-line-length=100]
    - id: check-docstring-first
    - id: check-ast
    - id: mixed-line-ending
    - id: requirements-txt-fixer