repos:
-   repo: https://github.com/ambv/black
    rev: 19.3b0
    hooks:
    - id: black
      language_version: python3.6

-   repo: https://github.com/PyCQA/bandit
    rev: 1.6.0
    hooks:
    - id: bandit
      args: [--skip=B101]

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    - id: check-merge-conflict
    - id: debug-statements
    - id: flake8
      args: [--max-line-length=100, --ignore=E402, --ignore=W503]
    - id: check-docstring-first
    - id: check-ast
    - id: mixed-line-ending
    - id: requirements-txt-fixer
