language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"  # 3.5 development branch
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  
# command to install dependencies
#install:
  #- pip install -r requirements.txt
  #- pip install .
  
# command to run tests
#script:
#  - pytest

notifications:
  email:
    recipients:
      - schimpfabian@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
